# Generated by Django 6.0.6 on 2026-08-17 02:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255,
                        verbose_name="รอบการรับสมัคร (เช่น TCAS 1 Portfolio)",
                    ),
                ),
                ("description", models.TextField(verbose_name="รายละเอียดการรับสมัคร")),
                ("start_date", models.DateField(verbose_name="วันเริ่มเปิดรับสมัคร")),
                ("end_date", models.DateField(verbose_name="วันสิ้นสุดรับสมัคร")),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        default="https://admission.sskru.ac.th",
                        verbose_name="ลิงก์ระบบรับสมัคร",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="เปิดรับสมัครอยู่"),
                ),
            ],
            options={
                "verbose_name": "ข้อมูลการรับสมัคร",
                "verbose_name_plural": "ข้อมูลการรับสมัคร",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="ContactInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dept_name",
                    models.CharField(
                        default="สาขาวิทยาการคอมพิวเตอร์",
                        max_length=255,
                        verbose_name="ชื่อสาขา",
                    ),
                ),
                (
                    "university",
                    models.CharField(
                        default="มหาวิทยาลัยราชภัฏศรีสะเกษ",
                        max_length=255,
                        verbose_name="ชื่อมหาวิทยาลัย",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        default="319 ถนนไทยพันทา ตำบลโพธิ์ อำเภอเมืองศรีสะเกษ จังหวัดศรีสะเกษ 33000",
                        verbose_name="ที่อยู่",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        default="045-643600 ต่อ 1234",
                        max_length=100,
                        verbose_name="เบอร์โทรศัพท์",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="cs@sskru.ac.th", max_length=254, verbose_name="อีเมล"
                    ),
                ),
                (
                    "facebook",
                    models.URLField(
                        default="https://www.facebook.com/ComputerScienceSSKRU",
                        verbose_name="Facebook Page",
                    ),
                ),
                (
                    "instagram",
                    models.URLField(
                        default="https://www.instagram.com/cs_sskru",
                        verbose_name="Instagram",
                    ),
                ),
                (
                    "youtube",
                    models.URLField(
                        default="https://www.youtube me.com/@CS_SSKRU",
                        verbose_name="YouTube",
                    ),
                ),
                (
                    "tiktok",
                    models.URLField(
                        default="https://www.tiktok.com/@cs_sskru",
                        verbose_name="TikTok",
                    ),
                ),
                (
                    "google_maps_url",
                    models.TextField(
                        default="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3862.684347585098!2d104.3315!3d15.1189!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3116e254e2f9d8ab%3A0x4464c20d75a894b9!2z4Lih4Lir4Liy4Lin4Li04LiX4Lii4Liy4Lil4Lix4Lii4Lij4Liy4LiK4Lmg4Lij4LmE4LiU4Lih4Liy4Lio4Lij4Li14LiB4Li14Lih4LmM!5e0!3m2!1sth!2sth!4v1700000000000!5m2!1sth!2sth",
                        verbose_name="Google Maps Embed URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "ข้อมูลการติดต่อสาขา",
                "verbose_name_plural": "ข้อมูลการติดต่อสาขา",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ชื่อหลักสูตร")),
                ("description", models.TextField(verbose_name="คำอธิบายหลักสูตร")),
                (
                    "duration",
                    models.CharField(
                        default="4 ปี", max_length=100, verbose_name="ระยะเวลาศึกษา"
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        default="วิทยาศาสตรบัณฑิต (วท.บ.)",
                        max_length=255,
                        verbose_name="ชื่อปริญญา",
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="ภาพประกอบหลักสูตร",
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        default="bi-code-slash",
                        max_length=100,
                        verbose_name="Bootstrap Icon Class",
                    ),
                ),
                (
                    "tech_tags",
                    models.CharField(
                        default="Python, Web, Cloud, AI",
                        max_length=255,
                        verbose_name="เทคโนโลยีที่เรียน",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="เปิดสอนอยู่"),
                ),
            ],
            options={
                "verbose_name": "หลักสูตร",
                "verbose_name_plural": "หลักสูตร",
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="ชื่อกิจกรรม/รูปภาพ"),
                ),
                (
                    "image",
                    models.CharField(max_length=500, verbose_name="URL/Path รูปภาพ"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("coding", "Coding & Development"),
                            ("workshop", "Workshop"),
                            ("hackathon", "Hackathon"),
                            ("competition", "การแข่งขัน"),
                            ("ai", "AI & Robotics"),
                            ("project", "โครงงานนักศึกษา"),
                            ("activities", "กิจกรรมสาขา"),
                        ],
                        default="activities",
                        max_length=50,
                        verbose_name="หมวดหมู่",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่เพิ่ม"),
                ),
            ],
            options={
                "verbose_name": "แกลเลอรีภาพ",
                "verbose_name_plural": "แกลเลอรีภาพ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="หัวข้อข่าว")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="URL Slug"
                    ),
                ),
                ("description", models.TextField(verbose_name="คำอธิบายย่อ")),
                ("content", models.TextField(verbose_name="เนื้อหาข่าวแบบละเอียด")),
                (
                    "image",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="รูปภาพประกอบ (URL/Static)",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("news", "ข่าวสาร"),
                            ("activity", "กิจกรรม"),
                            ("showcase", "ผลงานนักศึกษา"),
                            ("contest", "การแข่งขัน"),
                            ("workshop", "อบรม"),
                        ],
                        default="news",
                        max_length=50,
                        verbose_name="หมวดหมู่",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="วันที่เผยแพร่"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="อัปเดตล่าสุด"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="เผยแพร่"),
                ),
            ],
            options={
                "verbose_name": "ข่าวสารและกิจกรรม",
                "verbose_name_plural": "ข่าวสารและกิจกรรม",
                "ordering": ["-published_at"],
            },
        ),
    ]
