# Generated by Django 6.0.6 on 2026-08-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lecturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("asst_prof_dr", "ผู้ช่วยศาสตราจารย์ ดร."),
                            ("asst_prof", "ผู้ช่วยศาสตราจารย์"),
                            ("assoc_prof_dr", "รองศาสตราจารย์ ดร."),
                            ("dr", "ดร."),
                            ("mr", "อาจารย์"),
                        ],
                        default="dr",
                        max_length=30,
                        verbose_name="คำนำหน้า/ตำแหน่ง",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="ชื่อ (ภาษาไทย)"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="นามสกุล (ภาษาไทย)"),
                ),
                (
                    "full_name_en",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="ชื่อ-นามสกุล (ภาษาอังกฤษ)",
                    ),
                ),
                (
                    "photo_url",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="URL รูปภาพ"
                    ),
                ),
                (
                    "expertise",
                    models.CharField(
                        default="วิทยาการคอมพิวเตอร์",
                        max_length=255,
                        verbose_name="ความเชี่ยวชาญ",
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        default="bi-person-fill",
                        max_length=100,
                        verbose_name="Bootstrap Icon",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        default="อาจารย์ผู้รับผิดชอบหลักสูตร",
                        max_length=200,
                        verbose_name="บทบาทในหลักสูตร",
                    ),
                ),
                (
                    "is_head",
                    models.BooleanField(default=False, verbose_name="หัวหน้าสาขาวิชาฯ"),
                ),
                (
                    "profile_link",
                    models.URLField(
                        blank=True, default="", verbose_name="ลิงก์ประวัติวิชาการ"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=99, verbose_name="ลำดับการแสดงผล"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="แสดงบนเว็บไซต์"),
                ),
            ],
            options={
                "verbose_name": "อาจารย์ประจำหลักสูตร",
                "verbose_name_plural": "อาจารย์ประจำหลักสูตร",
                "ordering": ["order", "last_name"],
            },
        ),
    ]
